---
title: "Framework of a replicable Open Manufacturing Demonstration Facility supporting the INEDIT process"
subtitle: "D4.3. Monitoring and assessment of the demonstrator’s deployment based on the framework [UL] (M28)" 
description: | 
  Scientific and technical writing, native to the web
date: "`r Sys.Date()`"
author:
  - first_name: "Laurent"
    last_name: "Dupont"
    url: https://erpi.univ-lorraine.fr/people/Laurent-Dupont/
    affiliation: ERPI
    affiliation_url: https://erpi.univ-lorraine.fr/
    orcid_id: 0000-0002-8279-9690  
  - first_name: "Fréderique"
    last_name: "Mayer"
    url: https://erpi.univ-lorraine.fr/people/Frederique-Mayer/
    affiliation: ERPI
    affiliation_url: https://erpi.univ-lorraine.fr/
    orcid_id:     
  - first_name: "Hakim"
    last_name: "Boudaoud"
    url: https://erpi.univ-lorraine.fr/people/Hakim-Boudaoud/
    affiliation: ERPI
    affiliation_url: https://erpi.univ-lorraine.fr/
    orcid_id: 0000-0003-4452-5952
  - first_name: "Fabio"
    last_name: "Cruz"
    url: https://erpi.univ-lorraine.fr/people/Fabio-Cruz/
    affiliation: ERPI
    affiliation_url: https://erpi.univ-lorraine.fr/
    orcid_id: 0000-0001-8529-5327
  - first_name: "Fedoua"
    last_name: "Kasmi"
    url: https://erpi.univ-lorraine.fr/people/Fedoua-Kasmi/
    affiliation: ERPI
    affiliation_url: https://erpi.univ-lorraine.fr/
    orcid_id: 0000-0001-5159-0264
  - first_name: "Brunelle"
    last_name: "Marche"
    url: https://erpi.univ-lorraine.fr/people/Brunelle-Marche/
    affiliation: ERPI
    affiliation_url: https://erpi.univ-lorraine.fr/
    #orcid_id: 0000-0001-6328-1338
  - first_name: "Alex"
    last_name: "Gabriel"
    url: https://erpi.univ-lorraine.fr/people/Alex-Gabriel/
    affiliation: ERPI
    affiliation_url: https://erpi.univ-lorraine.fr/
    #orcid_id: 0000-0001-6328-1338
#bibliography: biblio.bib
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


```

```{r}

```


```{r}

```

