```{r In.depth.Analysis}


#Test = right_join(Test,  DIT %>% group_by(Phase, Process) %>% tally() %>% select(-n), by="Process" ) %>% select(Phase, Process, Activity:Partner ) 

Test2 = DIT %>% select(Process, Activities, Tasks) %>% set_names("Process", "Activity", "Task") %>% as_tibble()
Comparison = Test2 %>% select(Process, Activity) %>% anti_join(Test %>% select(Process, Activity)) %>% set_names("Process", "Activities")

Test2 = DIT %>% semi_join(.,  Comparison) %>% select(Process, Activities, Tasks ) %>% 
            mutate("Involved stakeholders" = NA,
                   "Input" = NA,
                   "Output" = NA,
                   "Technology/ Equipment" = NA,
                   "Technology's maturity" = NA,
                   "Skills" = NA,
                   "Skills' maturity" = NA,
                   "Practices" = NA,
                   "Partner"  = NA
                   ) %>%
     set_names("Process", "Activity", "Task", "Involved stakeholders", "Input", "Output", "Technology/ Equipment",
               "Technology's maturity", "Skills", "Skills' maturity", "Practices", "Partner")

names(Test2)

# Dataframe global
Indepth =  bind_rows(Test, Test2)
rm(Test, Test2) # deleting the variables 
Indepth = Indepth %>% dplyr::mutate(Partner = replace_na(Partner, "Not defined"))   
names(Indepth)

DIT %>% group_by(Process) %>% tally
Indepth %>% group_by(Process) %>% tally


A = Indepth %>% select(Partner, Process) %>% set_colnames(c("Source", "Target")) 
B = Indepth %>% select(Process, Activity ) %>%  set_colnames(c("Source", "Target")) 
C = Indepth %>% select(Activity, Task ) %>%  set_colnames(c("Source", "Target")) 
C$Target[C$Target==""] <- NA
C = na.omit(C)

Test = rbind(A, B, C) 
rm(A, B,C)
Test = Test %>% mutate(Value = c(1))

# From these flows we need to create a node data frame: it lists every entities involved in the flow
nodes <- data.frame( name=c(as.character(Test$Source), as.character(Test$Target)) %>% unique())

# With networkD3, connection must be provided using id, not using real name like in the links dataframe.. So we need to reformat it.
Test$IDsource <- match(Test$Source, nodes$name)-1 
Test$IDtarget <- match(Test$Target, nodes$name)-1


```

[See the picture in big size](https://lf2l.github.io/INEDIT-WP4/DIT-usecases/)

```{r include=TRUE, fig.width=10, fig.height=5}

#implication <- 
sankeyNetwork(Links = Test, Nodes = nodes,
              Source = "IDsource", Target = "IDtarget", 
              Value = "Value", NodeID = "name",  fontSize = 15, #LinkGroup="Group",# NodeGroup="Group",
              sinksRight=FALSE,
              nodeWidth = 30,
              height = 500,
              width = 1000,
              nodePadding = 1
              )


#to Jpg
#saveWidget(as_widget(implication), "implication.html", selfcontained = TRUE)
#webshot2::webshot(url = "implication.html", file= "Implication.png" , vwidth = 1800, vheight = 1300)


```



