```{r}
unames <- Data %>% names()
Participation.DIT <- Data %>% set_names(unames) %>% map("Participation DIT") %>% enframe()

Test = Participation.DIT %>% mutate(Process = value %>% map(. %>%  names()  )) %>%
   select(-value) %>% tidyr::unnest(Process)

Test = right_join(Test,  DIT %>% group_by(Phase, Process) %>% tally() %>% select(-n), by="Process" ) %>% select(Phase, Process, name) 


A = Test %>% select(Phase, Process) %>% set_colnames(c("Source", "Target")) %>%  mutate(Group = "DIT") 
B = Test %>% select(Process, name) %>%  set_colnames(c("Source", "Target"))
B$Target[is.na(B$Target)]<-"No User Case"
B$Group = B$Target


Test = rbind(A,B)
Test = Test %>% mutate(Value = c(1))
Test$Group = as.factor(Test$Group)

# From these flows we need to create a node data frame: it lists every entities involved in the flow
nodes <- data.frame(
   name=c(as.character(Test$Source), as.character(Test$Target)) %>% unique()
)
nodes$Group <- as.factor(c("my_unique_group"))

# With networkD3, connection must be provided using id, not using real name like in the links dataframe.. So we need to reformat it.
Test$IDsource <- match(Test$Source, nodes$name)-1 
Test$IDtarget <- match(Test$Target, nodes$name)-1

# Give a color for each group:
#my_color <- 'd3.scaleOrdinal() .domain(["DIT", "AIMEN"", "UL", "UNNINOVA", "VERA",  "No User Case" ]) .range(["#69b3a2", "steelblue", "grey", "red", "green", "grey" ])'

rm(A,B)

```


```{r include=TRUE, fig.width=8}
sankeyNetwork(Links = Test, Nodes = nodes,
              Source = "IDsource", Target = "IDtarget", 
              Value = "Value", NodeID = "name",  fontSize = 20, LinkGroup="Group", # NodeGroup="Group",
              sinksRight=FALSE,
              height=500, width=1000
              )
```
